### ISSUE TITLE
Why is `gcc-4.9` explicitly used?

### ISSUE THREAD

**Issue by rileyweber13** [jeffhammond/STREAM#2]
I noticed that commit 5d77d6ddb explicitly specifies GCC 4.9 in the makefile. I'm sure you have a good reason, but I don't see it. Could you explain your choice? Is there a reason to install GCC 4.9 instead of using whatever version was included in my operating system?

**Comment by jeffhammond** [comment]
There is no good reason for this and you should just use the GCC available to you on your system, ideally the latest.  Sorry for the inconvenience.

I set the version explicitly a long time ago because of MacOS and using Homebrew compilers rather than GCC Dragonegg on top of Apple Clang.  Since I am using the branches with machine-specific parameters for all of my experiments now anyways, I didn't bother fixing it in the main branch.

**Comment by rileyweber13** [comment]
fixed with #3
